/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-11 12:46:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class editBill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Edit Bills</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">Edit Billing Records</h2>\r\n");
      out.write("\r\n");
      out.write("<!--Navbar start-->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">HMS Billing System</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link active\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"loadAppointments\">Patients-List</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"billing.jsp\">Billing Page</a></li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"viewBills.jsp\">View Bills</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!--Navbar End-->\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Bar -->\r\n");
      out.write("    <form method=\"get\" action=\"editBill.jsp\" class=\"input-group mb-4\">\r\n");
      out.write("        <input type=\"text\" name=\"search\" class=\"form-control\"\r\n");
      out.write("               placeholder=\"Search by Patient Name or Bill ID\">\r\n");
      out.write("        <button class=\"btn btn-primary\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    ");

        String search = request.getParameter("search");
        String billToEdit = request.getParameter("bill_id");

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/hms", "root", "root"
        );
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Edit Form -->\r\n");
      out.write("    ");

        if(billToEdit != null){
            PreparedStatement ps = con.prepareStatement(
                "SELECT * FROM billing WHERE bill_id = ?"
            );
            ps.setInt(1, Integer.parseInt(billToEdit));
            ResultSet e = ps.executeQuery();

            if(e.next()){
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card mb-5\">\r\n");
      out.write("        <div class=\"card-header bg-warning\">\r\n");
      out.write("            <strong>Edit Bill #");
      out.print( e.getInt("bill_id") );
      out.write("</strong>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <form action=\"updateBill\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"bill_id\" value=\"");
      out.print( e.getInt("bill_id") );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Patient Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"pname\" class=\"form-control\"\r\n");
      out.write("                           value=\"");
      out.print( e.getString("patient_name") );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Doctor Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"dname\" class=\"form-control\"\r\n");
      out.write("                           value=\"");
      out.print( e.getString("doctor_name") );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\">Appointment Date</label>\r\n");
      out.write("                    <input type=\"date\" name=\"adate\" class=\"form-control\"\r\n");
      out.write("                           value=\"");
      out.print( e.getDate("appointment_date") );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row mb-3\">\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <label>Consultation Fee</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.01\" name=\"cfee\" class=\"form-control\"\r\n");
      out.write("                               value=\"");
      out.print( e.getDouble("consultation_fee") );
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <label>Medicine Charges</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.01\" name=\"mcharge\" class=\"form-control\"\r\n");
      out.write("                               value=\"");
      out.print( e.getDouble("medicine_charges") );
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <label>Room Charges</label>\r\n");
      out.write("                        <input type=\"number\" step=\"0.01\" name=\"rcharge\" class=\"form-control\"\r\n");
      out.write("                               value=\"");
      out.print( e.getDouble("room_charges") );
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success\">Update Bill</button>\r\n");
      out.write("                <a href=\"editBill.jsp\" class=\"btn btn-secondary\">Cancel</a>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

            }
        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- List of All Bills -->\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <div class=\"card-header bg-dark text-white\">All Billing Records</div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("            <table class=\"table table-bordered table-hover\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Bill ID</th>\r\n");
      out.write("                        <th>Patient</th>\r\n");
      out.write("                        <th>Doctor</th>\r\n");
      out.write("                        <th>Date</th>\r\n");
      out.write("                        <th>Total</th>\r\n");
      out.write("                        <th>Edit</th>\r\n");
      out.write("                        <th>Delete</th>   <!-- ð¥ New column -->\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        PreparedStatement ps2;

                        if(search != null && !search.trim().isEmpty()){
                            ps2 = con.prepareStatement(
                              "SELECT * FROM billing WHERE patient_name LIKE ? OR bill_id LIKE ?"
                            );
                            ps2.setString(1, "%" + search + "%");
                            ps2.setString(2, "%" + search + "%");
                        } else {
                            ps2 = con.prepareStatement("SELECT * FROM billing ORDER BY bill_id DESC");
                        }

                        ResultSet rs = ps2.executeQuery();
                        while(rs.next()){
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( rs.getInt("bill_id") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("patient_name") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getString("doctor_name") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getDate("appointment_date") );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( rs.getDouble("total_amount") );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <a href=\"editBill.jsp?bill_id=");
      out.print( rs.getInt("bill_id") );
      out.write("\"\r\n");
      out.write("                               class=\"btn btn-warning btn-sm\">\r\n");
      out.write("                                Edit\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                        <!-- ð¥ NEW DELETE BUTTON -->\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <a href=\"deleteBill?bill_id=");
      out.print( rs.getInt("bill_id") );
      out.write("\"\r\n");
      out.write("                               onclick=\"return confirm('Are you sure you want to delete this bill?');\"\r\n");
      out.write("                               class=\"btn btn-danger btn-sm\">\r\n");
      out.write("                                Delete\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
