/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-11 11:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import register_patients.Patient;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("register_patients.Patient");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hospital Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Navigation Bar -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Hospital Management System</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" onclick=\"showSection('dashboard')\">Dashboard</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick=\"showSection('patients')\">Patients</a></li>\r\n");
      out.write("                <li><a href=\"loadPatients\">Patients List</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick=\"showSection('appointments')\">Appointments</a></li>\r\n");
      out.write("                <li><a href=\"loadAppointments\">Appointments List</a></li>\r\n");
      out.write("                <li><a href=\"billing.jsp\">Billing System</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick=\"showSection('tokens')\">Token System</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- Chatbox -->\r\n");
      out.write("<!-- <div class=\"chatbox\" id=\"chatbox\">\r\n");
      out.write("    <div class=\"chat-header\" onclick=\"toggleChat()\">ð¬ Chat with us</div>\r\n");
      out.write("    <div class=\"chat-body\" id=\"chat-body\">\r\n");
      out.write("        <div class=\"messages\" id=\"messages\"></div>\r\n");
      out.write("        <input type=\"text\" id=\"chat-input\" placeholder=\"Type a message...\" />\r\n");
      out.write("        <button onclick=\"sendMessage()\">Send</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Dashboard Section -->\r\n");
      out.write("   <section id=\"dashboard\" class=\"section active\">\r\n");
      out.write("    <h2>Dashboard</h2>\r\n");
      out.write("    <p>Welcome to the Hospital Management System! Use the navigation menu to manage patients, appointments, and tokens.</p>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slideshow -->\r\n");
      out.write("    <div class=\"slideshow-container\">\r\n");
      out.write("        <img class=\"slide\" src=\"image.jpg\" alt=\"Hospital Image 1\">\r\n");
      out.write("        <img class=\"slide\" src=\"image1.jpg\" alt=\"Hospital Image 2\">\r\n");
      out.write("        <img class=\"slide\" src=\"image2.jpg\" alt=\"Hospital Image 3\">\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Patient Registration Section -->\r\n");
      out.write("    <section id=\"patients\" class=\"section\">\r\n");
      out.write("        <h2>Register New Patient</h2>\r\n");
      out.write("        <form id=\"patientForm\" action=\"register\" method=\"post\">\r\n");
      out.write("            <label>Full Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"pname\" name=\"pname\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Age:</label>\r\n");
      out.write("            <input type=\"number\" id=\"page\" name=\"page\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Gender:</label>\r\n");
      out.write("            <select id=\"pgender\" name=\"pgender\">\r\n");
      out.write("                <option  value=\"male\">Male</option>\r\n");
      out.write("                <option value=\"female\">Female</option>\r\n");
      out.write("                <option value=\"other\">Other</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label>Contact:</label>\r\n");
      out.write("            <input type=\"text\" id=\"pcontact\" name=\"pcontact\" required>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Appointment Section -->\r\n");
      out.write("    <section id=\"appointments\" class=\"section\">\r\n");
      out.write("        <h2>Book Appointment</h2>\r\n");
      out.write("        <form id=\"appointmentForm\" action=\"bookappointment\" method=\"post\">\r\n");
      out.write("            <label>Patient Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"aname\" name=\"aname\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Doctor:</label>\r\n");
      out.write("            <select id=\"adoctor\" name=\"adoctor\">\r\n");
      out.write("                <option value=\"Dr. Sharma (Cardiologist)\">Dr. Sharma (Cardiologist)</option>\r\n");
      out.write("                <option value=\"Dr. Patel (Dermatologist)\">Dr. Patel (Dermatologist)</option>\r\n");
      out.write("                <option value=\"Dr. Verma (General Physician)\">Dr. Verma (General Physician)</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label>Date:</label>\r\n");
      out.write("            <input type=\"date\" id=\"adate\" name=\"adate\" required>\r\n");
      out.write("\r\n");
      out.write("            <!-- <button type=\"submit\">Book</button> -->\r\n");
      out.write("            <input type=\"submit\" value=\"Book Appointment\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    <!-- Token System Section -->\r\n");
      out.write("    <section id=\"tokens\" class=\"section\">\r\n");
      out.write("        <h2>Token System</h2>\r\n");
      out.write("        <p>Click below to generate a token for the next patient.</p>\r\n");
      out.write("        <button id=\"generateToken\">Generate Token</button>\r\n");
      out.write("        <h3>Current Token: <span id=\"tokenDisplay\">0</span></h3>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
