/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-17 13:08:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import jakarta.servlet.http.HttpSession;

public final class staffDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Staff Dashboard</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body{\r\n");
      out.write("            min-height:100vh;\r\n");
      out.write("            background: linear-gradient(135deg,#141e30,#243b55);\r\n");
      out.write("            color:#fff;\r\n");
      out.write("        }\r\n");
      out.write("        .glass-card{\r\n");
      out.write("            backdrop-filter: blur(14px);\r\n");
      out.write("            background: rgba(255,255,255,0.15);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            border:1px solid rgba(255,255,255,0.3);\r\n");
      out.write("            box-shadow:0 10px 35px rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .circle-img{\r\n");
      out.write("            width:180px;\r\n");
      out.write("            height:180px;\r\n");
      out.write("            border-radius:50%;\r\n");
      out.write("            object-fit:cover;\r\n");
      out.write("            border:4px solid rgba(255,255,255,0.6);\r\n");
      out.write("        }\r\n");
      out.write("        .form-control, .form-select{\r\n");
      out.write("            background: rgba(255,255,255,0.25);\r\n");
      out.write("            border:none;\r\n");
      out.write("            color:#fff;\r\n");
      out.write("        }\r\n");
      out.write("        .form-select option{ color:#000; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    /* ---------------- SESSION CHECK ---------------- */
    HttpSession sess = request.getSession(false);
    if(sess == null || sess.getAttribute("staffId") == null){
        response.sendRedirect("staffPortal.jsp");
        return;
    }

    String staffId   = sess.getAttribute("staffId").toString();
    String staffName = sess.getAttribute("staffName").toString();

    /* ---------------- DB CHECK ---------------- */
    boolean profileExists = false;
    String stream = "";
    String role   = "";

    try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/hms","root","root");

        String sql = "SELECT stream, role FROM staff_profiles WHERE staff_id=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, staffId);
        ResultSet rs = ps.executeQuery();

        if(rs.next()){
            profileExists = true;
            stream = rs.getString("stream");
            role   = rs.getString("role");
        }
        rs.close(); ps.close(); con.close();
    }catch(Exception e){ }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= ONE TIME FORM ================= -->\r\n");
      out.write("    ");
 if(!profileExists){ 
      out.write("\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-7\">\r\n");
      out.write("            <div class=\"glass-card p-4\">\r\n");
      out.write("                <h3 class=\"text-center\">One Time Fill up Form</h3>\r\n");
      out.write("                <p class=\"text-center text-warning\">In case wrong data, contact admin</p>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"StaffProfileServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"mt-2\">Stream / Expertise</label>\r\n");
      out.write("                    <select class=\"form-select mb-3\" name=\"stream\" required onchange=\"updateOptions(this.value)\">\r\n");
      out.write("                        <option value=\"\">-- Select Stream --</option>\r\n");
      out.write("                        <option value=\"Medical\">Medical</option>\r\n");
      out.write("                        <option value=\"Hospital Management\">Hospital Management</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                    <label>Role</label>\r\n");
      out.write("                    <select class=\"form-select mb-3\" name=\"role\" id=\"roleSelect\" required>\r\n");
      out.write("                        <option value=\"\">-- Select Role --</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                    <label>Capture / Upload Photo</label>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("    <video id=\"video\" width=\"300\" height=\"230\" autoplay class=\"rounded border\"></video>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" onclick=\"capturePhoto()\">\r\n");
      out.write("        Capture Photo\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<canvas id=\"canvas\" width=\"300\" height=\"230\" style=\"display:none;\"></canvas>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"photoBase64\" id=\"photoBase64\" required>\r\n");
      out.write("                    <button class=\"btn btn-success w-100\">Submit Profile</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ================= DASHBOARD ================= -->\r\n");
      out.write("    ");
 if(profileExists){ 
      out.write("\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-10\">\r\n");
      out.write("            <div class=\"glass-card p-4\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-4 text-center\">\r\n");
      out.write("                        <img src=\"LoadStaffImageServlet?staffId=");
      out.print(staffId);
      out.write("\" class=\"circle-img\" alt=\"Profile\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-8\">\r\n");
      out.write("                        <h4>Welcome, ");
      out.print(staffName);
      out.write("</h4>\r\n");
      out.write("                        <p><b>Staff ID:</b> ");
      out.print(staffId);
      out.write("</p>\r\n");
      out.write("                        <p><b>Stream:</b> ");
      out.print(stream);
      out.write("</p>\r\n");
      out.write("                        <p><b>Role:</b> ");
      out.print(role);
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("                <h5>Current Patients Allotted / Booked</h5>\r\n");
      out.write("                <table class=\"table table-dark table-bordered mt-3\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Patient ID</th>\r\n");
      out.write("                            <th>Name</th>\r\n");
      out.write("                            <th>Ward</th>\r\n");
      out.write("                            <th>Status</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <!-- Future Implementation -->\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function updateOptions(stream){\r\n");
      out.write("    let role = document.getElementById(\"roleSelect\");\r\n");
      out.write("    role.innerHTML = '<option value=\"\">-- Select Role --</option>';\r\n");
      out.write("\r\n");
      out.write("    if(stream === \"Medical\"){\r\n");
      out.write("        addOptions(role,[\"Surgeon\",\"Paramedic\",\"Lab Technician\",\"Nurse\",\"Ward Boy\",\"Dresser\",\"Compounder\"]);\r\n");
      out.write("    }\r\n");
      out.write("    if(stream === \"Hospital Management\"){\r\n");
      out.write("        addOptions(role,[\"MD\",\"Supervisor\",\"Apparatus-Technician\",\"Medical Store Incharge\"]);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function addOptions(select, arr){\r\n");
      out.write("    arr.forEach(v=>{\r\n");
      out.write("        let o=document.createElement(\"option\");\r\n");
      out.write("        o.value=v; o.text=v; select.appendChild(o);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("let video = document.getElementById(\"video\");\r\n");
      out.write("let canvas = document.getElementById(\"canvas\");\r\n");
      out.write("let photoBase64 = document.getElementById(\"photoBase64\");\r\n");
      out.write("\r\n");
      out.write("navigator.mediaDevices.getUserMedia({ video: true })\r\n");
      out.write(".then(stream => {\r\n");
      out.write("    video.srcObject = stream;\r\n");
      out.write("})\r\n");
      out.write(".catch(err => {\r\n");
      out.write("    alert(\"Camera access denied\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function capturePhoto() {\r\n");
      out.write("    let context = canvas.getContext(\"2d\");\r\n");
      out.write("    context.drawImage(video, 0, 0, canvas.width, canvas.height);\r\n");
      out.write("    photoBase64.value = canvas.toDataURL(\"image/png\");\r\n");
      out.write("    alert(\"Photo Captured Successfully\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
