/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-17 11:42:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class staffPortal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>HMS Staff Portal</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Glass card styling */\r\n");
      out.write("        .glass-card {\r\n");
      out.write("            backdrop-filter: blur(14px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(14px);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.18);\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("            box-shadow: 0 8px 30px rgba(0, 0, 0, 0.35);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .glass-header {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control {\r\n");
      out.write("            background: rgba(255,255,255,0.25);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control::placeholder {\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-glass {\r\n");
      out.write("            background: rgba(255,255,255,0.25);\r\n");
      out.write("            border: 1px solid rgba(255,255,255,0.4);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-glass:hover {\r\n");
      out.write("            background: rgba(255,255,255,0.45);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5\">\r\n");
      out.write("    <h2 class=\"text-center text-white mb-5\">Hospital Management System – Staff Portal</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row g-4 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Login Card -->\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"glass-card\">\r\n");
      out.write("                <div class=\"glass-header\">Login to Profile</div>\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <form action=\"StaffLoginServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"text\" name=\"staffId\" class=\"form-control mb-3\" placeholder=\"Staff ID\" required>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" class=\"form-control mb-3\" placeholder=\"Password\" required>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-glass w-100\">Login</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Register Card -->\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"glass-card\">\r\n");
      out.write("                <div class=\"glass-header\">Register to Portal</div>\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <form action=\"StaffRegisterServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"text\" name=\"name\" class=\"form-control mb-2\" placeholder=\"Full Name\" required>\r\n");
      out.write("                        <input type=\"text\" name=\"staffId\" class=\"form-control mb-2\" placeholder=\"Staff ID\" required>\r\n");
      out.write("                        <input type=\"email\" name=\"email\" class=\"form-control mb-2\" placeholder=\"Email\" required>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" class=\"form-control mb-3\" placeholder=\"Password\" required>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-glass w-100\">Register</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Notices Card -->\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"glass-card\">\r\n");
      out.write("                <div class=\"glass-header\">Staff Notices</div>\r\n");
      out.write("                <div class=\"p-4\">\r\n");
      out.write("                    <ul class=\"list-unstyled small\">\r\n");
      out.write("                        <li>• Staff meeting at 3:00 PM</li>\r\n");
      out.write("                        <li>• New duty roster uploaded</li>\r\n");
      out.write("                        <li>• ID cards verification pending</li>\r\n");
      out.write("                        <li>• Emergency drill on Friday</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
