/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-11 13:17:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class viewBills_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Billing Records</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body { background: #f2f4f8; }\r\n");
      out.write("    .bill-card { border-radius: 15px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }\r\n");
      out.write("    .table thead { background: #0d6efd; color: white; }\r\n");
      out.write("    .table-hover tbody tr:hover { background: #eef3ff; }\r\n");
      out.write("    .search-box { border-radius: 30px; padding-left: 20px; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"text-center mb-4\">\r\n");
      out.write("        <h2 class=\"fw-bold\">Hospital Billing Records</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("	<!--Navbar start-->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">HMS Billing System</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link active\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"loadAppointments\">Patients-List</a></li>\r\n");
      out.write("        <li class=\"nav-item\"><a class=\"nav-link\" href=\"billing.jsp\">Billing Page</a></li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"editBill.jsp\">Edit Bills</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<!--Navbar End-->\r\n");
      out.write("    <div class=\"card bill-card\">\r\n");
      out.write("        <div class=\"card-header bg-dark text-white d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <span class=\"fw-bold\">All Billing Records</span>\r\n");
      out.write("            <a href=\"billing.jsp\" class=\"btn btn-sm btn-light\">+ Create New Bill</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card-body p-0\">\r\n");
      out.write("            <table class=\"table table-bordered table-hover mb-0\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Bill ID</th>\r\n");
      out.write("                        <th>Patient</th>\r\n");
      out.write("                        <th>Doctor</th>\r\n");
      out.write("                        <th>Date</th>\r\n");
      out.write("                        <th>Consultation</th>\r\n");
      out.write("                        <th>Medicine</th>\r\n");
      out.write("                        <th>Room</th>\r\n");
      out.write("                        <th>Total (RS)</th>\r\n");
      out.write("                        <th style=\"width:130px;\">Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");

                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "root");

                        String search = request.getParameter("search");
                        PreparedStatement ps;

                        if(search != null && !search.trim().isEmpty()){
                            ps = con.prepareStatement(
                                "SELECT * FROM billing WHERE patient_name LIKE ? OR doctor_name LIKE ? OR bill_id LIKE ? ORDER BY bill_id DESC"
                            );
                            ps.setString(1, "%" + search + "%");
                            ps.setString(2, "%" + search + "%");
                            ps.setString(3, "%" + search + "%");
                        } else {
                            ps = con.prepareStatement("SELECT * FROM billing ORDER BY bill_id DESC");
                        }

                        ResultSet rs = ps.executeQuery();
                        boolean empty = true;

                        while(rs.next()){
                            empty = false;
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td><strong>#");
      out.print( rs.getInt("bill_id") );
      out.write("</strong></td>\r\n");
      out.write("                        <td id=\"pname");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getString("patient_name") );
      out.write("</td>\r\n");
      out.write("                        <td id=\"dname");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getString("doctor_name") );
      out.write("</td>\r\n");
      out.write("                        <td id=\"adate");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getDate("appointment_date") );
      out.write("</td>\r\n");
      out.write("                        <td id=\"cfee");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getDouble("consultation_fee") );
      out.write("</td>\r\n");
      out.write("                        <td id=\"mcharge");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getDouble("medicine_charges") );
      out.write("</td>\r\n");
      out.write("                        <td id=\"rcharge");
      out.print( rs.getInt("bill_id") );
      out.write('"');
      out.write('>');
      out.print( rs.getDouble("room_charges") );
      out.write("</td>\r\n");
      out.write("                        <td class=\"fw-bold text-success\" id=\"total");
      out.print( rs.getInt("bill_id") );
      out.write("\">\r\n");
      out.write("                            Rs. ");
      out.print( rs.getDouble("total_amount") );
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button class=\"btn btn-danger btn-sm w-100\" \r\n");
      out.write("                                    onclick=\"openRemarksModal(");
      out.print( rs.getInt("bill_id") );
      out.write(")\">Print PDF</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 if(empty){ 
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"9\" class=\"text-center text-muted py-4\">No billing records found.</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Remarks Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"remarksModal\" tabindex=\"-1\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\">Add Remarks Before Printing</h5>\r\n");
      out.write("        <button class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <textarea id=\"remarksText\" class=\"form-control\" rows=\"4\"\r\n");
      out.write("                  placeholder=\"Enter remarks that will appear in the PDF\"></textarea>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("        <button class=\"btn btn-primary\" onclick=\"generatePDF()\">Generate PDF</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("let selectedBillData = {};\r\n");
      out.write("\r\n");
      out.write("function openRemarksModal(button){\r\n");
      out.write("    selectedBillData.patient = button.getAttribute(\"data-patient\");\r\n");
      out.write("    selectedBillData.doctor = button.getAttribute(\"data-doctor\");\r\n");
      out.write("    selectedBillData.date = button.getAttribute(\"data-date\");\r\n");
      out.write("    selectedBillData.cfee = parseFloat(button.getAttribute(\"data-cfee\")) || 0;\r\n");
      out.write("    selectedBillData.mcharge = parseFloat(button.getAttribute(\"data-mcharge\")) || 0;\r\n");
      out.write("    selectedBillData.rcharge = parseFloat(button.getAttribute(\"data-rcharge\")) || 0;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('remarksText').value = \"\";\r\n");
      out.write("    let modal = new bootstrap.Modal(document.getElementById('remarksModal'));\r\n");
      out.write("    modal.show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function generatePDF(){\r\n");
      out.write("    const pdf = new jsPDF({ orientation: \"portrait\", unit: \"mm\", format: \"a4\" });\r\n");
      out.write("\r\n");
      out.write("    // HEADER\r\n");
      out.write("    pdf.setFontSize(20);\r\n");
      out.write("    pdf.text(\"HMS - Hospital Bill\", 105, 20, { align: \"center\" });\r\n");
      out.write("\r\n");
      out.write("    // PATIENT DETAILS\r\n");
      out.write("    pdf.setFontSize(12);\r\n");
      out.write("    pdf.text(`Patient Name: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.patient}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 40);\r\n");
      out.write("    pdf.text(`Doctor: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.doctor}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 50);\r\n");
      out.write("    pdf.text(`Appointment Date: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.date}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 60);\r\n");
      out.write("    pdf.text(`Consultation Fee: Rs ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.cfee}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 80);\r\n");
      out.write("    pdf.text(`Medicine Charges: Rs ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.mcharge}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 90);\r\n");
      out.write("    pdf.text(`Room Charges: Rs ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.rcharge}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 100);\r\n");
      out.write("    const total = (selectedBillData.cfee + selectedBillData.mcharge + selectedBillData.rcharge).toFixed(2);\r\n");
      out.write("    pdf.text(`Total Amount: Rs ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, 20, 115);\r\n");
      out.write("\r\n");
      out.write("    // REMARKS\r\n");
      out.write("    const remarks = document.getElementById('remarksText').value || \"No remarks provided.\";\r\n");
      out.write("    pdf.setFontSize(14);\r\n");
      out.write("    pdf.text(\"Remarks:\", 20, 140);\r\n");
      out.write("    pdf.setFontSize(12);\r\n");
      out.write("    pdf.text(remarks, 20, 150);\r\n");
      out.write("\r\n");
      out.write("    pdf.save(`Bill_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedBillData.patient}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".pdf`);\r\n");
      out.write("\r\n");
      out.write("    // Store into DB\r\n");
      out.write("    savePDFLog(selectedBillData.patient, remarks);\r\n");
      out.write("\r\n");
      out.write("    // Close modal\r\n");
      out.write("    bootstrap.Modal.getInstance(document.getElementById('remarksModal')).hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function savePDFLog(patientName, remarks){\r\n");
      out.write("    fetch(\"storePDFLog\", {\r\n");
      out.write("        method: \"POST\",\r\n");
      out.write("        headers: { \"Content-Type\": \"application/x-www-form-urlencoded\" },\r\n");
      out.write("        body: \"patient_name=\" + encodeURIComponent(patientName) +\r\n");
      out.write("              \"&remarks=\" + encodeURIComponent(remarks)\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
