/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-12-11 11:12:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import register_patients.Patient;

public final class viewPatientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("register_patients.Patient");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hospital Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    	#editBTN {\r\n");
      out.write("    background-color: #4CAF50; /* Green */\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 6px 12px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#editBTN:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#deleteBTN {\r\n");
      out.write("    background-color: #f44336; /* Red */\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 6px 12px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#deleteBTN:hover {\r\n");
      out.write("    background-color: #da190b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-color: rgba(0,0,0,0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".popup-content {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    width: 300px;\r\n");
      out.write("    margin: 10px auto;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!-- Navigation Bar -->\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Hospital Management System</h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"index.jsp\" onclick=\"showSection('dashboard')\">Dashboard</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp\" onclick=\"showSection('patients')\">Patients</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp\" onclick=\"showSection('appointments')\">Appointments</a></li>\r\n");
      out.write("                <li><a href=\"#\">Billing System</a></li>\r\n");
      out.write("                <li><a href=\"index.jsp\" onclick=\"showSection('tokens')\">Token System</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("     <h3>Patient List</h3>\r\n");
      out.write("        <table id=\"patientTable\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Name</th>\r\n");
      out.write("                    <th>Age</th>\r\n");
      out.write("                    <th>Gender</th>\r\n");
      out.write("                    <th>Contact</th>\r\n");
      out.write("                    <th>Actions</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                \r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("             ");

            List<Patient> patient = (List<Patient>) session.getAttribute("patientsList");
            if (patient != null && !patient.isEmpty()) {
                for (Patient p : patient) {
        
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( p.getName() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( p.getAge() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( p.getGender() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( p.getContact() );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("    				<form action=\"editPatient\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("       					 <input type=\"hidden\" name=\"contact\" value=\"");
      out.print( p.getContact() );
      out.write("\">\r\n");
      out.write("       					 <button id=\"editBTN\" type=\"button\"\r\n");
      out.write("						    onclick=\"openEditPopup('");
      out.print( p.getName() );
      out.write("', \r\n");
      out.write("						    '");
      out.print( p.getAge() );
      out.write("', \r\n");
      out.write("						    '");
      out.print( p.getGender() );
      out.write("',\r\n");
      out.write("						     '");
      out.print( p.getContact() );
      out.write("')\">\r\n");
      out.write("						    Edit\r\n");
      out.write("						 </button>\r\n");
      out.write("   					 </form>\r\n");
      out.write("	\r\n");
      out.write("				    <form action=\"deletePatient\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("				        <input type=\"hidden\" name=\"contact\" value=\"");
      out.print( p.getContact() );
      out.write("\">\r\n");
      out.write("				        <button id=\"deleteBTN\" type=\"submit\" onclick=\"return confirm('Are you sure you want to delete this patient?');\">Delete</button>\r\n");
      out.write("						\r\n");
      out.write("				    </form>\r\n");
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("        ");

                }
            } else {
        
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"4\" style=\"text-align:center;\">No records found</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div id=\"editPopup\" class=\"popup\">\r\n");
      out.write("  <div class=\"popup-content\">\r\n");
      out.write("    <h3>Edit Patient</h3>\r\n");
      out.write("    <form id=\"editForm\" action=\"editRecord\" method=\"post\">\r\n");
      out.write("      <input type=\"hidden\" id=\"originalContact\" name=\"originalContact\">\r\n");
      out.write("\r\n");
      out.write("      <label>Name:</label>\r\n");
      out.write("      <input type=\"text\" id=\"editName\" name=\"name\" required><br>\r\n");
      out.write("\r\n");
      out.write("      <label>Age:</label>\r\n");
      out.write("      <input type=\"number\" id=\"editAge\" name=\"age\" required><br>\r\n");
      out.write("\r\n");
      out.write("      <label>Gender:</label>\r\n");
      out.write("      <select id=\"editGender\" name=\"gender\">\r\n");
      out.write("        <option value=\"male\">Male</option>\r\n");
      out.write("        <option value=\"female\">Female</option>\r\n");
      out.write("        <option value=\"other\">Other</option>\r\n");
      out.write("      </select><br>\r\n");
      out.write("\r\n");
      out.write("      <label>Contact:</label>\r\n");
      out.write("      <input type=\"text\" id=\"editContact\" name=\"contact\" required><br>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\" id=\"editBTN\">Save Changes</button>\r\n");
      out.write("      <button type=\"button\" onclick=\"closeEditPopup()\">Cancel</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("       <script>\r\n");
      out.write("function openEditPopup(name, age, gender, contact) {\r\n");
      out.write("    document.getElementById(\"editPopup\").style.display = \"block\";\r\n");
      out.write("    document.getElementById(\"editName\").value = name;\r\n");
      out.write("    document.getElementById(\"editAge\").value = age;\r\n");
      out.write("    document.getElementById(\"editGender\").value = gender;\r\n");
      out.write("    document.getElementById(\"editContact\").value = contact;\r\n");
      out.write("    document.getElementById(\"originalContact\").value = contact;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeEditPopup() {\r\n");
      out.write("    document.getElementById(\"editPopup\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("       \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
